### ISSUE TITLE
Error running docsearch

### ISSUE THREAD

**Issue by blee1170** [algolia/docsearch-scraper#305] opened 2016-07-15 06:59 UTC
I am getting this error when I try to run docsearch to scrape my site:

```
12:27:47 (master) docsearch-scraper: ./docsearch run ../../docsearch/config.json
Traceback (most recent call last):
  File "scraper/src/index.py", line 5, in <module>
    from config_loader import ConfigLoader
  File "/Users/z001n2j/temp/git/docsearch-scraper/scraper/src/config_loader.py", line 26, in <module>
    from .strategies.abstract_strategy import AbstractStrategy
ValueError: Attempted relative import in non-package
```

Any idea what could be causing it?

**Comment by ElPicador** [comment] 2016-07-15 07:36
@ercolanelli-leo Do you have an idea?

**Comment by ercolanelli-leo** [comment] 2016-07-15 08:09
@ElPicador Yes I see where it comes from, fixing it ASAP

**Comment by blee1170** [comment] 2016-07-15 09:55
Let me know if you want me to test something.

**Comment by ercolanelli-leo** [comment] 2016-07-15 11:19
PR here https://github.com/algolia/docsearch-scraper/pull/306

**Comment by blee1170** [comment] 2016-07-16 10:54
I pull the branch down and gave it a test and got this error:

```
16:23:31 (refactor-single-package) docsearch-scraper: ./docsearch run ../git/docsearch-scraper/config.json
Traceback (most recent call last):
  File "./docsearch", line 3, in <module>
    from scraper.cli.index import run
  File "/Users/z001n2j/temp/docsearch-scraper/scraper/cli/index.py", line 14, in <module>
    from .commands.bootstrap_config import BootstrapConfig
  File "/Users/z001n2j/temp/docsearch-scraper/scraper/cli/commands/bootstrap_config.py", line 2, in <module>
    from ...deployer.config_creator import create_config
  File "/Users/z001n2j/temp/docsearch-scraper/scraper/deployer/config_creator.py", line 7, in <module>
    from .html_helper import get_main_selector
  File "/Users/z001n2j/temp/docsearch-scraper/scraper/deployer/html_helper.py", line 4, in <module>
    from scrapy.linkextractors.lxmlhtml import LxmlLinkExtractor
  File "/Users/z001n2j/Library/Python/2.7/lib/python/site-packages/scrapy/__init__.py", line 34, in <module>
    from scrapy.spiders import Spider
  File "/Users/z001n2j/Library/Python/2.7/lib/python/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/Users/z001n2j/Library/Python/2.7/lib/python/site-packages/scrapy/http/__init__.py", line 12, in <module>
    from scrapy.http.request.rpc import XmlRpcRequest
  File "/Users/z001n2j/Library/Python/2.7/lib/python/site-packages/scrapy/http/request/rpc.py", line 7, in <module>
    from six.moves import xmlrpc_client as xmlrpclib
ImportError: cannot import name xmlrpc_client
```

I guess that there is still something off?

**Comment by maxiloc** [comment] 2016-07-16 11:10
@blee1170 The import error you have does not seem related to the docsearch scraper code but to scrapy. Did you do a  `pip install -r requirements.txt`. I'll check later today see if I can reproduce

**Comment by blee1170** [comment] 2016-07-16 11:13
I just re-ran the command in the branch (just to make sure). but no change. I am also doing it with the --user option because of El Capitan love/hate with python.

Command I ran:
```
pip install -r requirements.txt --user
```

**Comment by blee1170** [comment] 2016-07-16 11:30
I did a brew install of python and re-ran the pip install. That fixed the above error, but now there is a new one:

```
16:58:56 (refactor-single-package) docsearch-scraper: ./docsearch run ../git/docsearch-scraper/config.json
Traceback (most recent call last):
  File "./docsearch", line 5, in <module>
    run()
  File "/Users/z001n2j/temp/docsearch-scraper/scraper/cli/index.py", line 185, in run
    exit(command.run(sys.argv[2:]))
  File "/Users/z001n2j/temp/docsearch-scraper/scraper/cli/commands/run_config.py", line 22, in run
    return run_config(args[0])
TypeError: run_config() takes exactly 2 arguments (1 given)
```

**Comment by ercolanelli-leo** [comment] 2016-07-16 11:49
Yes my bad, a quickfix that should not have been that quick. It should be ok now

**Comment by ercolanelli-leo** [comment] 2016-07-16 11:49
Yes my bad, a quickfix that should not have been that quick. It should be ok now

**Comment by blee1170** [comment] 2016-07-16 12:45
Yep, that seems to have fixed it. But now I hit another problem. Our doc pages that I want to index are in a git enterprise repo (github pages). And it is failing because it needs to authenticate. Any way past that? Can I add a git token or something?

**Comment by maxiloc** [comment] 2016-07-16 12:53
Right now we don't have anything built in for that. I guess you could set js_render to true, if your firefox is logged in it should work.
That for sure something we need to work on

**Comment by blee1170** [comment] 2016-07-16 12:59
I enabled that. But however selenium is launching, its not getting my firefox session info. So it basically gets the same error.

**Comment by maxiloc** [comment] 2016-07-16 13:08
Is the login page accessible from internet ?
I had a prototype a few month back. If can you send me the link, I can work on this

**Comment by blee1170** [comment] 2016-07-16 13:21
I will have to check if I could give out the page (company rules might restrict it). It is a github enterprise LDAP auth with 2 factor. But I can get tokens to use for auth which would make it easier.

Sorry for the less then helpful option.

**Comment by maxiloc** [comment] 2016-07-16 13:23
Ok meanwhile I'll see what I can do with a double auth website. I'll keep you updated

**Comment by blee1170** [comment] 2016-07-16 13:24
Thanks for you awesome support on this.

**Comment by maxiloc** [comment] 2016-07-16 13:48
Just pushed the `auth-website` branch, which allow to open the sign-in page for x seconds before crawling. Can you try it and tell me if it works for you ?

Example with algolia dashboard, which is behind two factor for me:
```
{
  "index_name": "test",
  "start_urls": [
    "https://www.algolia.com/explorer#?index=wp_posts_post"
  ],
  "selectors": {
    "lvl0": "#facets-wrapper h3"
  },
  "login": {
    "url": "https://www.algolia.com/users/sign_in",
    "time": 20
  },
  "js_render": true,
  "js_wait": 5
}
```

**Comment by blee1170** [comment] 2016-07-16 14:03
Yep that worked for me! Although I did not get any records, but I am sure that is just my config.

Again, awesome support. This will help me get me POC further along.

**Comment by maxiloc** [comment] 2016-07-16 14:09
Your welcome.
I am merging it to master then, we might change it a bit because it's a bit painful to login at each crawl, I rather have it automatic (at least for login page with double auth), but I think this is the most generic we can do.

**Comment by blee1170** [comment] 2016-07-16 14:10
Oh don't get me wrong, I totally want a automatic way to do the auth as well. But for right now its at least something.

**Comment by blee1170** [comment] 2016-08-01 19:42
Has there been anymore thought on how to deal with a site that has two factor? Or in my case git that could be used with a token?

**Comment by maxiloc** [comment] 2016-08-01 19:55
I don't think of any way to handle two factor.
Login page is doable for sure.

**Comment by blee1170** [comment] 2016-08-01 20:08
So I just looked into the git documentation a bit more, and I can pass the token as the password. So that would fix my two factor problem if I could just pass a username/password.

**Comment by maxiloc** [comment] 2016-08-01 20:20
Ok I am going to bootstrap something during this week. I'll keep you updated

**Comment by blee1170** [comment] 2016-08-01 20:20
Fantastic!

**Comment by maxiloc** [comment] 2016-09-07 11:10
I am a bit late, sorry about that, gonna work on that asap

**Comment by maxiloc** [comment] 2016-09-20 10:08
Closing this, we have an on-going PR about this

**Closed by maxiloc** 2016-09-20 10:08 UTC
